# Site settings
title: Aris Zhang
email: 1461206118@qq.com
url: https://zyhacquaintance.github.io
description: "Coming from pkusz..."

# Color settings (hex-codes without the leading hash-tag)
color:
  primary-dark: '#000000'
  links: '#219ab3'

# Footer settings
footer: Aris

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: https://twitter.com/Arishary624
  - title: github
    url: https://github.com/zyhacquaintance

# Build settings
markdown: kramdown
permalink: pretty
